const TIME_START='TIME_START'
const TIME_CLEAR='TIME_CLEAR'
const TIME_STOP='TIME_STOP'
const ADD_DELETTIMES='ADD_DELETTIMES'
const SHOW_TYPING='SHOW_TYPING'
const CHANG_TO_1='CHANG_TO_1'
const CHANG_TO_2='CHANG_TO_2'
const CHANG_TO_3='CHANG_TO_3'
const CHANG_TO_4='CHANG_TO_4'
const CHANG_TO_5='CHANG_TO_5'
const CHANG_TO_6='CHANG_TO_6'
const CHANG_TO_7='CHANG_TO_7'
const CHANG_TO_8='CHANG_TO_8'

export default {
	TIME_START,
	TIME_CLEAR,
	ADD_DELETTIMES,
	SHOW_TYPING,
	TIME_STOP,
	CHANG_TO_1,
	CHANG_TO_2,
	CHANG_TO_3,
	CHANG_TO_4,
	CHANG_TO_5,
	CHANG_TO_6,
	CHANG_TO_7,
	CHANG_TO_8
}