const TIME_START='TIME_START'
const TIME_CLEAR='TIME_CLEAR'
const ADD_DELETTIMES='ADD_DELETTIMES'
const SHOW_TYPING='SHOW_TYPING'

export default {
	TIME_START,
	TIME_CLEAR,
	ADD_DELETTIMES,
	SHOW_TYPING
}